# Generated by Django 4.0.1 on 2022-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('genre', models.CharField(choices=[('non-fiction', 'non-fiction'), ('science-fiction', 'science-fiction'), ('fantasy', 'fantasy'), ('fairy-tale', 'fairy-tale'), ('fiction', 'fiction')], max_length=100)),
                ('date_filmed', models.DateField()),
            ],
        ),
    ]
