# Generated by Django 4.0.1 on 2022-01-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_filmed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
